### ISSUE TITLE
Validator identicons not displayed

### ISSUE THREAD

**Issue by bjornwgnr** [paritytech/substrate-telemetry#102]
https://telemetry.polkadot.io/#/Alexander
<img width="779" alt="screenshot 2019-01-31 at 22 19 10" src="https://user-images.githubusercontent.com/17831185/52086095-52797080-25a6-11e9-9621-fd22084ada5f.png">

**Comment by maciejhirsz** [comment]
Waiting on https://github.com/paritytech/oo7/pull/90 to fix
