### ISSUE TITLE
Question: How to integrate new RPC endpoint

### ISSUE THREAD

**Issue by gterzian** [paritytech/substrate-telemetry#120]
Looking at https://github.com/paritytech/substrate-telemetry/pull/119/files, however that seems to be using the websocket feed, and I haven't found the code that deals with RPC queries. 

I'm looking to integrate https://github.com/paritytech/substrate/pull/1884 into the UI...

Would anyone have some pointers? @maciejhirsz @cmichi

**Comment by maciejhirsz** [comment]
I'll close this since we've figure it out on chat.
