### ISSUE TITLE
Ghost nodes.

### ISSUE THREAD

**Issue by crsCR** [paritytech/substrate-telemetry#166]
I only run 1 node but telemetry is saying I have 3 (3x 'crs' with same Network ID, local IP and ports showing in Network State - 2x 'ghosts' not processing blocks). I've tried stop/starting the process and turning off server - the ghosts stay. 

It might have something to do with use of app validate / stop validating account actions. Not sure for 1st ghost (first noticed yesterday) but for 2nd, I stopped process this morning - after restarting process I refreshed and checked my account status and saw the 'validate' option available so, thinking I'd been removed as validator (had some downtime yesterday when trying to lose the 1st ghost), I clicked it... But, maybe there was actually just some delay in the app page updating - and clicking 'validate' while I was already validating created a ghost somehow. (2nd ghost appeared at this time, iirc.)

My best guess at cause of issue. Don't remember doing it but chance I created the 1st ghost same way...

EDIT: 

I've just tried to duplicate another error/ghost but, as I'm stuck in unbonding (I stopped validating and unbonded trying to see if I could lose the ghosts) I can't bond again to validate. Unless the unbond can be cancelled or someone wants to send me enough DOTs to validate again, can't try confirm... Above described process might not be cause of issue - I didn't watch what was going on carefully enough to say for sure.

**Comment by maciejhirsz** [comment]
Hey @crsCR, I just deployed an update to the server that should fix these. Can you report within the next few days if this still happens?

**Comment by crsCR** [comment]
Ghost nodes have gone now - but I can't check if can replicate what I think caused issue...

**Comment by maciejhirsz** [comment]
Seems fine since the deploy, server has been stable too, so gonna close this.

**Comment by crsCR** [comment]
Cause of issue linked to this, maybe: https://github.com/polkadot-js/apps/issues/1343
