### ISSUE TITLE
yarn

### ISSUE THREAD

**Issue by IPSE-TEAM** [paritytech/substrate-telemetry#169]
error /data/substrate-telemetry/node_modules/blake2js: Command failed.

yarn version 1.17.3

**Comment by crsCR** [comment]
Same error + various warnings...

**Comment by maciejhirsz** [comment]
@IPSE-TEAM or @crsCR - can you post your node versions and/or other environment details?

**Comment by crsCR** [comment]
NVM v0.34.0, Polkadot v0.5.1, Ubuntu 18.04 - anything else?
