### ISSUE TITLE
Allow for sorting by attributes

### ISSUE THREAD

**Issue by soc1c** [paritytech/substrate-telemetry#172]
With 150+ nodes on the Kusama dashboard refreshing every couple of seconds it's really hard to find a specific node. 

It would be nice to be able to adjust the sorting of the node list, i.e., by name.

ref https://github.com/paritytech/polkadot/issues/416

**Comment by lsaether** [comment]
You can do this already, just start typing on the Telemetry screen and it will filter for whatever you've typed.

**Comment by soc1c** [comment]
Ah, I would have never guessed that.

I was trying to CTRL+F my way around
