### ISSUE TITLE
Pick "Best Block" only from validators

### ISSUE THREAD

**Issue by bkchr** [paritytech/substrate-telemetry#175]
Today we had a reorg of the chain of around 200 blocks "back". Now the validators started to build new blocks with lower numbers, but you could still see the old best number. Would be nice if we somehow could just show the best number send by a validator.

**Comment by bkchr** [comment]
Okay, it is probably a different problem as highlighted by @andresilva. Telemetry just shows the highest imported block number, not the best block number.

**Comment by maciejhirsz** [comment]
This is a pretty old issue, as things are now there is no way for telemetry to verify that a node is really a validator. There is already a mechanism in place such that if the chain stalls at a high(er) block number and doesn't move, and there are blocks being produced at lower height, then after time any node on the dead fork will drop down in the table.

Timeout for that is currently set to 15 minutes, but I think I can tweak it down to something closer to a minute (given average block time on all chains is basically below 10 seconds anyway).
