### ISSUE TITLE
Cannot build with docker-compose

### ISSUE THREAD

**Issue by StakerSpace** [paritytech/substrate-telemetry#203]
Following the README on with docker and separate front and back-end cannot get the telemetry to start. Where before I could launch commit `31784131d607c6b009e2d7abcf1ed94b04830916` with docker-compose.

With the latest commit when starting the docker-compose I get the following log, the front-end run, but the back-end doesn't after giving a successful creation 

```
Successfully built 408134d651ef
Successfully tagged substrate-telemetry_telemetry-backend:latest
Creating substrate-telemetry_telemetry-frontend_1 ... done
Creating substrate-telemetry_telemetry-backend_1  ... done
root@vmi308712:~/repo/substrate-telemetry# docker ps
CONTAINER ID        IMAGE                                    COMMAND                  CREATED             STATUS              PORTS                    NAMES
e6a4eb504d5d        substrate-telemetry_tdeelemetry-frontend   "docker-entrypoint.s…"   14 seconds ago      Up 9 seconds        0.0.0.0:3000->3000/tcp   substrate-telemetry_telemetry-frontend_1
```

When building them seperate on the latest commit and starting them seperately, the back-end feed is listening to 8000 and the front-end runs on port 3000. My servers are pointing to websocket 1024, would this be the problem ?

**Comment by ilhanu** [comment]
Not using the docker version with the latest when changing my url to : `--telemetry-url ws://localhost:8000/submit` It shows the connceted node in the logs of the back-end. 

It doesn't show on the front-end of the telemetry with `yarn start:frontend`  it stays. How do I start up the front-end so I can see the node info ?

**Comment by StakerSpace** [comment]
Not using the docker version with the latest when changing my url to : `--telemetry-url ws://localhost:8000/submit` It shows the connceted node in the logs of the back-end. 

It doesn't show on the front-end of the telemetry with `yarn start:frontend`  it stays. How do I start up the front-end so I can see the node info ?

**Comment by maciejhirsz** [comment]
@StakerSpace thanks for the report, docker-compose needs to be updated to run the Rust backend. Your manual install looks like it should work, especially with the node showing up in the backend logs, what exactly do you see in the frontend? Is there a red icon in the top right corner?

**Comment by woss** [comment]
this [PR](https://github.com/paritytech/substrate-telemetry/pull/226) fixes that
