### ISSUE TITLE
Back-end feed doesn't pass on to front-end

### ISSUE THREAD

**Issue by StakerSpace** [paritytech/substrate-telemetry#228]
I tried to get the new docker-compose. The builds work fine, however I don't see any information on the built front-end page:

![image](https://user-images.githubusercontent.com/48808256/74093538-67e77b80-4ad3-11ea-9cfd-8d79c34df831.png)

In the docker logs of the back-end I do see feed accepting the node telemetry information. 

```
telemetry-backend_1   | 2020-02-08 23:23:27,169 INFO  [telemetry::chain] [Kusama CC3] [1/0] new best block (36093) 0x4dbb252520c4e26c8869b27cf6f77c7fff7710514681a861a7e3803c4c2a442a
telemetry-backend_1   | 2020-02-08 23:23:27,201 INFO  [telemetry::chain] [Kusama CC3] [1/0] new best block (36094) 0xb3f55973f7e688710f05bab4b4079b2aa3b22b016a46d7518f4f23fa80eb4d28
telemetry-backend_1   | 2020-02-08 23:23:27,234 INFO  [telemetry::chain] [Kusama CC3] [1/0] new best block (36095) 0xb8ad9ecbf92e8ec9fe473eda0d6ca0b372005f6896f11f4016fc18a7b258c168
telemetry-backend_1   | 2020-02-08 23:23:27,273 INFO  [telemetry::chain] [Kusama CC3] [1/0] new best block (36096) 0xb1bbf74f2bbafbbf4b8d292e591b7b738cd9839f87d118a0b163954aa61b582d
telemetry-backend_1   | 2020-02-08 23:23:27,313 INFO  [telemetry::chain] [Kusama CC3] [1/0] new best block (36097) 0xcc24c4b25c9a9c6675acc540e50fe3d2b632e74b2e42896c7d14177ad8b3fb06
telemetry-backend_1   | 2020-02-08 23:23:27,342 INFO  [telemetry::chain] [Kusama CC3] [1/0] new best block (36098) 0xda88d15c50e3634333950344f98b9fde5b1b659521365ddc2a64cde3094629a1
```

**Comment by StakerSpace** [comment]
I just tested it on my local machine and there it functions fine, so this problem is only on the node it was installed on. what might cause this?

**Comment by woss** [comment]
what do you mean  by 

>  so this problem is only on the node it was installed on.

**Comment by StakerSpace** [comment]
> what do you mean by
> 
> > so this problem is only on the node it was installed on.

I'm using a vps (contabo) to run telemetry and that is what I meant by "node", as running it on my local machine with a local dev chain does work. I'm trying a different vps provider now, to see if it's vps provider.

**Comment by woss** [comment]
Let's see did I got it right.
Telemetry UI is running on the node
Telemetry Server is running on the node.
If that is the case your ws address should point to the IP address of your node like so `IP:8000` not `127.0.0.1:8000` 

Look  at this piece of code in [Connections.ts](https://github.com/paritytech/substrate-telemetry/blob/master/packages/frontend/src/Connection.ts#L21)
```
  private static readonly address = window.location.protocol === 'https:'
                                      ? `wss://${window.location.hostname}/feed/`
                                      : `ws://127.0.0.1:8000/feed`;
```
This says that if it's https use the `PROD` version where it is asumed that you have stuff set up securely, otherwise failback to `localhost`

If you don't have the certificates( https ) just change the `127.0.0.1:8000` to your node public IP and you should be fine

**Comment by StakerSpace** [comment]
This solved it, thank you! 

However I don't understand why the localhost (ws://127.0.0.1:8000/feed/)wont work. The public ip is binded to the localhost feed.

**Comment by woss** [comment]
because it is the nature of the frontend apps. it was trying to connect to YOUR localhost not the SERVER. because the web apps run in your browser on your computer.
