### ISSUE TITLE
Filter by genesis hash

### ISSUE THREAD

**Issue by bkchr** [paritytech/substrate-telemetry#263]
The telemetry should filter by genesis hash for known networks like `Kusama`, `Westend`, `Polkadot`, etc.

We have restarted `Westend` quite some time ago, but some nodes still produce blocks on the old network. These nodes should not be visible on the `Westend` network tab. We could use the genesis hash to ensure that nodes are reporting indeed for the correct network.

**Comment by bkchr** [comment]
@maciejhirsz can you please take care of this?

**Comment by maciejhirsz** [comment]
@bkchr sorry, I was on holidays in-between this being submitted and now and didn't catch up. I'm looking into it now, and there is no genesis hash submitted by nodes to the telemetry. It should be trivial to add it to `system.connected` I reckon.

**Comment by bkchr** [comment]
@maciejhirsz as we now send the genesis hash, could we now get this feature? :D

**Comment by maciejhirsz** [comment]
@bkchr yeah, I'll put that into the refactoring of #310, should happen sometime in the next 2 weeks, pending on progress on jsonrpsee :)

**Comment by bkchr** [comment]
Ty  :)
