### ISSUE TITLE
Search / filter network by name

### ISSUE THREAD

**Issue by xlc** [paritytech/substrate-telemetry#276]
Currently networks are sorted by node account, so it is almost impossible to locate a network with low node count. There are just no deterministic order.

Will be useful if there is a way to filter network by name.

**Comment by lovelaced** [comment]
I would love to see this, right now it's hard to find smaller test networks in the big long list :)

**Comment by jsdw** [comment]
This obviously doesn't look the part, but would it suffice to have a "filter chain" input along the top of the big list, with a couple of sort options (a-z asc/desc and node count asc/desc) at bubbles that you can toggle?

<img width="1154" alt="Screenshot 2021-12-10 at 16 58 20" src="https://user-images.githubusercontent.com/3799193/145612310-6fd7e98b-d1e9-4f9f-925e-5ac4be4e652d.png">

**Comment by lovelaced** [comment]
That would be great as a first step (and functionally complete :D)

I'm not a UI designer but the narrow chain-picker has always felt a little weird to me, like it's not using as much real-estate as it could. maybe some sort of matrix view of chains with a search bar at the top would be cool. i can't mock up for the life of me but something like this with smaller items (sorry if this is a terrible idea)

![terrible](https://user-images.githubusercontent.com/8581604/145624930-073d0dba-da2f-47a4-be2f-56b4539359de.png)

**Comment by jsdw** [comment]
I think something like that would be great! I'd def be inclined to pretty up that whole modal as part of this task (my "mockup" with just the laziest possible way to show what I meant via a bit of HTML injection :D)

**Comment by jsdw** [comment]
I had a go at this; see #440 for a couple of screenshots and to leave any feedback :)
