### ISSUE TITLE
How to change the icon of client version in telemetry website?

### ISSUE THREAD

**Issue by MyronFanQiu** [paritytech/substrate-telemetry#302]
Is there any config in chain's code to change the icon of version in telemetry website? Or it's a centralized config of telemetry website?
![截屏2020-12-09 下午3 27 41](https://user-images.githubusercontent.com/49134743/101599241-6c9ef800-3a34-11eb-902e-9ec4b0422605.png)

**Comment by maciejhirsz** [comment]
@MyronFanQiu You'll need to open a PR here. Include an svg of the icon in `frontend/src/icons` and plug it in [`ImplementationColumn.tsx`](https://github.com/paritytech/substrate-telemetry/blob/1f5b1607cca0ecc8dc1efa237a7f40d3ab3e5291/frontend/src/components/List/Column/ImplementationColumn.tsx#L7-L49) (this needs to match the string name of the node implementation for which you'd like to have a custom icon).
