### ISSUE TITLE
repeatedly getting 522 errors through cloudflare.

### ISSUE THREAD

**Issue by 2075** [paritytech/substrate-telemetry#328]
telemetry seems a little overwhelmed, anything we can do?
also our (ZERO.IO) nodes receive plenty of timeout errors when connecting.

![image](https://user-images.githubusercontent.com/1140449/112687523-e938d380-8e77-11eb-83f5-b4383765de58.png)

**Comment by dvdplm** [comment]
Indeed we’ve had some issues and downtime yesterday, so sorry about that. It is back now and should be a little more stable. 
Closing this one now, but feel free to re-open if you experience further issues. Thanks!
