### ISSUE TITLE
env-config.js not found

### ISSUE THREAD

**Issue by NukeManDan** [paritytech/substrate-telemetry#334]
The top level `index.html` has [a reference](https://github.com/paritytech/substrate-telemetry/blob/089352c73eb1ac9103486e801b2f6bced86df4ac/frontend/public/index.html#L9) to `env-config.js` that is also in the `.gitignore` list (as it should be). 

But this leads to an error, as there is no prompt to generate this file, or (better) check to see if it exists and warn/ignore it if so. This is in the console on startup:

```
Uncaught SyntaxError: expected expression, got '<'
```

**Comment by chevdor** [comment]
Hey @NukeManDan,
I would have to double check the following but the file you mention may be a generated file allowing to pass ENV.

**Comment by chevdor** [comment]
See https://github.com/paritytech/substrate-telemetry/blob/master/frontend/env.sh

**Comment by chevdor** [comment]
This is [where](https://github.com/paritytech/substrate-telemetry/pull/240/files#diff-ea60ef29f6f537c1c83468c00b60de28f86e06edfe4a3d91274723c6f298fdb8R31) the env-config.js is generated

The background is that we wanted a static site (smaller, simpler, etc...) but that means obviously no server and nothing to load the env. When using node in dev mode, this is taken care of for you, when using docker, there is a script that generated this js file that the static HTML can load to get the ENV from docker.

If you run directy from the console, you should be in node dev mode. Not sure what the context is but we can have a chat :)

**Comment by jsdw** [comment]
It's worth noting that some of the way this works is changing as a result of recent work to add Helm charts and such for deployment of this to our internal services. We'll have to review the Dockerfiles and steps now I think to make sure that it can still be deployed using Docker/docker-compose independently, as it might be that the README needs a tweak to accomodate these changes.

**Comment by chevdor** [comment]
@jsdw noted. Make sure you keep the feature that allows passing ENV variables to the UI (see [also this comment](https://github.com/paritytech/substrate-telemetry/pull/240#issuecomment-606096510)), that will be useful in K8S as well. This feature is also useful for internal networks.

**Comment by chevdor** [comment]
@NukeManDan could you share the exact command you used to produce this issue?

**Comment by jsdw** [comment]
@chevdor yup, definitely! The changes made so far have just tweaked the frontend Dockerfile to not generate that env-config.js file, and instead it's being mounted via a configmap (which the frontend still picks up).

I haven't had a chance today, but I'll have a pass over things next week and make sure that local docker and the readme are still correct!

**Comment by chevdor** [comment]
Did you ensure this still works? It may not complain, instead it would only ignore your ENV and use the defaults.

The generation of the `env-config.js` file was made to allow injecting ENV into an nginx running static content. I don't think the only fact of using  of a configmap solves the issue.

I see you could have the `env-config.js` in a configmap and mount it in place, this would work,  but this option makes it harder for "regular" docker users where using ENV (and giving then defaults) is IMO much easier.

**Comment by jsdw** [comment]
It has been tested to work, yup. I definitely hear you re ease of use with the "standard" docker containers. I'll keep this in mind when I look over things; it might be that I can revert the Dockerfile changes, as offhand I don't see why we can't just keep the previous docker approach for ease of docker usage, and then blat it with a configmap for our k8s stuff.

**Comment by chevdor** [comment]
Yep, that sounds like a good option.

Also, it is more standard and expected to pass some ENV to a container (docker or k8s) than to pass *some* file with a specific expected content.

What *could* be improved over the blanket filling of **ALL** the ENV into the file would be to filter and pick only those starting with `SUBSTRATE_TELEMETRY_`. That would prevent providing some potentially sensitive ENV to **some** container. Again not an issue for k8s but this is safer for someone setting up a local docker on a bare metal machine.

**Comment by chevdor** [comment]
Scratch my last comment about improving, this is [already done](https://github.com/paritytech/substrate-telemetry/blob/master/frontend/env.sh#L11).

**Comment by chevdor** [comment]
@NukeManDan thanks for taking the time to report this issue and sorry for the confusion.
So the `env-config.js` you found missing, used to be generated (and thus always there) but was removed (causing the problem you saw). The issue has been closed in #368 and I did test and confirm that the feature (ie bring the ENV into the JS env under `window.process_env` is working fine again with #368 merged in.

I am closing this issue but please re-open if you still see this somewhere.
