### ISSUE TITLE
Make UI subscribe by genesis hash, not chain label

### ISSUE THREAD

**Issue by jsdw** [paritytech/substrate-telemetry#350]
Chain labels change and are based on whatever the most common label for a given chain that's been seen is.

The UI subscribes to chains by their label, but these labels could change at any time.

This requires the backend to maintain an uptodate mapping from chain label to chain details, so that it knows which chain a subscription is about. We run the risk of this mapping falling out of sync with reality, or of potential race conditions between a UI "subscribe to chain" message and a chain label changing (however improbabale).

I'd propose that we provide genesis hashes to the UI along with labels/node counts, and have the UI use those when subscribing to chains. This should reduce backend complexity and the scope for races.

**Comment by chevdor** [comment]
That's a good idea but how do you propose handling the case of a chain fork?
Both chains would have the same genesis hash but we end up talking about 2 different chains.
Having the genesis hash as well could be usefull though.
