### ISSUE TITLE
Document what verbosity is and does

### ISSUE THREAD

**Issue by chevdor** [paritytech/substrate-telemetry#357]
-[ ] error here: https://github.com/paritytech/substrate-telemetry#terminal-3---node

**Comment by jsdw** [comment]
With the recent merge of the sharding docs, I added a line of help in this area already ("Note: The "0" at the end of the URL is a verbosity level, and not part of the URL itself. Verbosity levels range from 0-9, with 0 denoting the lowest verbosity."). Is that sufficient to have this issue closed?

**Comment by chevdor** [comment]
Yep that totally works for me. I would add a comment (if still relevant) that both url and verbosity need to be quoted together as I saw that as a common issue. ie: `--telemetry-url <url> <verbosity>` vs `--telemetry-url '<url> <verbosity>'`.
If you could link the new doc/commit with the fix, we could close that right away.

**Comment by jsdw** [comment]
Closed by #368 :)
