### ISSUE TITLE
Almost empty list for Moonbase Alpha

### ISSUE THREAD

**Issue by crystalin** [paritytech/substrate-telemetry#378]
Looking at https://telemetry.polkadot.io/#list/Moonbase%20Alpha, there are currently 3 nodes only reported (out of the 500 nodes).
I quickly looked at the console, no error and the websocket response for `subscribe:Moonbase Alpha` only reports those nodes it seems

**Comment by sea212** [comment]
[Zeitgeist telemetry information](https://telemetry.polkadot.io/#list/Zeitgeist%20Battery%20Park) is also not displayed properly. The nodes are working as expected and not outputting any error messages. Somehow I managed to get the page to show the correct list one time and the Zeitgeist tab at the top of the page also seems to show the correct number of nodes connected via telemetry, so I assume the information is available to the server but cannot be displayed for some reason.

**Comment by maciejhirsz** [comment]
@crystalin @sea212 This should be fixed now, be advised the networks are now addressed by genesis hash:

Moonbase: https://telemetry.polkadot.io/#list/0x91bc6e169807aaa54802737e1c504b2577d4fafedd5a02c10293b1cd60e39527
Zeitgeist: https://telemetry.polkadot.io/#list/0xb0a8d493285c2df73290dfb7e61f870f17b41801197a149ca93654499ea3dafe

Feel free to reopen the issue if there is anything we've missed :)

**Comment by crystalin** [comment]
Thank you @maciejhirsz , I confirm it works
