### ISSUE TITLE
CI doesn't appear to run for (at least some) frontend PRs

### ISSUE THREAD

**Issue by jsdw** [paritytech/substrate-telemetry#393]
No Frontend CI for:

https://github.com/paritytech/substrate-telemetry/pull/391
https://github.com/paritytech/substrate-telemetry/pull/387

Frontend CI did run for:

https://github.com/paritytech/substrate-telemetry/pull/364

Possibly related to some difference in merging from external remotes vs merging from origin?

The same may be true of backend PRs, so it's worth making sure both work as expected when digging into this.

**Comment by jsdw** [comment]
Thanks for the pointer; that sounds like the thing to do to me! 

I dug into the docs a little more, and this page seems quite relevant:

https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull-request-events-for-forked-repositories

From there, there is also some detail about needing to approve workflow runs from external forks (I suppose so that other users can't maliciously trigger loads of CI workflows in your repository):

https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks

My vote would be to just try adding the `on.pull_request` bits as well as you suggest, and see what happens (I'm sure I've seen that on other repositories we host as well) :)

**Comment by jsdw** [comment]
I've added the `on.pull_request` now in the above, so this is ready to test and hopefully close.

**Comment by CYBAI** [comment]
@jsdw Yes! I just rebased https://github.com/paritytech/substrate-telemetry/pull/391 to master and it works now! Thank you for the fix!

![image](https://user-images.githubusercontent.com/6782666/132206104-b18982fc-3039-4d59-af3d-c61b55c8dc13.png)

**Comment by jsdw** [comment]
Awesome, thank you for testing that! I'll close this now :)
