### ISSUE TITLE
Khala Network peers bringing huge amount of dummy nodes in Telemetry

### ISSUE THREAD

**Issue by h4x3rotab** [paritytech/substrate-telemetry#403]
We have observed a huge amount of nodes showing on Kusama Telemetry page. Till the end of yesterday, we have seen 900k nodes. Most of the newly added nodes are at block #0, and each node shows for 10-20 times with the same name.

We suspect most of them come from Khala clients. Before we launched our secure enclave mining, in my impression the Kusama Telemetry board looks normal (no confirmation). However after our launch, it quickly goes beyond 100k, and approached 900k nodes yesterday. Some nodes have the nodes indicating they are Khala miners.

Khala mining requires each miner to sync a Khala full node, which comes with a full Kusama node as well. So theoretically, we should bring the amount of Kusama nodes up to the number of our miners. However the Telemetry shows duplicated miners and out-of-date nodes, which is problematic.

This is our Khala chain-spec where the telemetry endpoint was defined. It should load the unmodified Kusama chain-spec in a parachain client as well:

<https://github.com/Phala-Network/khala-parachain/blob/main/node/res/khala.json>

**Comment by jsdw** [comment]
I haven't seen this be an issue recently, so I'll close the issue now and we can re-open it if there appears to be a problem again :)
