### ISSUE TITLE
Feature request: favicon

### ISSUE THREAD

**Issue by lovelaced** [paritytech/substrate-telemetry#425]
I know, I know - it doesn't matter that much :) but it would be nice to have to easily identify telemetry in a sea of browser tabs.

**Comment by dvdplm** [comment]
<img width="797" alt="Screenshot 2022-01-11 at 11 46 09" src="https://user-images.githubusercontent.com/18515/148928679-e8247503-6728-4cb5-98ea-81ffabdb3c84.png">

**Comment by jsdw** [comment]
Closed by https://github.com/paritytech/substrate-telemetry/pull/451
