### ISSUE TITLE
afg.finalized being read by substrate-telemetry, but not being sent by substrate

### ISSUE THREAD

**Issue by kishansagathiya** [paritytech/substrate-telemetry#427]
`afg.finalized` being read by substrate-telemetry, but not being sent by substrate. I am saying that by searching for `afg.finalized` in substrate code. Is that the case?
 Why so? I substrate-telemetry expecting telemetry from any other parties?

**Comment by jsdw** [comment]
Interesting! I also can't find any reference to "aura.pre_sealed_block", which is ignored but known about by telemetry.

My guess without checking would be that these were once emitted in older versions of substrate but aren't any longer.

We should probably remove them. (I'm not sure but I wonder whether "afg.finalized" became "afg.finalized_blocks_up_to" at some point, or whether we should handle the latter like wecurrently do the former)

**Comment by jsdw** [comment]
We trimmed down the messages that telemetry looks for somewhat recently, including removing any that were no logner sent, so I'll close this now. Thanks for highlighting it! :)
