### ISSUE TITLE
Why are some telemetry messages being sent by substrate, but not supported by substrate-telemetry?

### ISSUE THREAD

**Issue by kishansagathiya** [paritytech/substrate-telemetry#430]
substrate-telemetry has a limited list of message types (`NodeMessage`), that it can read. Substrate sends a lot more messages than that. Why is substrate sending those messages?
I checked through issues in `substrate-telemetry` and did not find anything about supporting the remaining message types. Is there any plans of supporting those messages?

Or are they being supported and I am missing something?

**Comment by al3mart** [comment]
I guess @dvdplm will be able to give you more info on this topic.

For now, I think it will be helpful if you specify which messages types are speaking about

**Comment by jsdw** [comment]
The telemetry that a substrate based node is capable of emitting is fairly general purpose in scope, and is not intended to be consumed solely by this service and nothing else. As with many substrate things, the ability to emit telemetry is fairly generic I think, and so you can make use of that in your own substrate-based deployments however you wish.

This is simply one possible application which captures and displays some aspects of a node's telemetry output, and simply ignores the messages it has no interest in :)
