### ISSUE TITLE
Docker image name is incomplete in example commands in readme.md, commands fail due to this

### ISSUE THREAD

**Issue by yayoi-k** [paritytech/substrate-telemetry#437]
The docker image name is missing the proceeding "parity/" in step #2 and #3 under heading [Run the backend and frontend using docker-compose](https://github.com/paritytech/substrate-telemetry#run-the-backend-and-frontend-using-docker-compose)

The correct image name is: parity/substrate-telemetry-backend

If one runs the docker commands as written in step #2 and #3 in the readme.md they will fail due to the image name.  Here is the excerpt from readme.md with problem image names bolded:

Start up the backend core process. We expose port 8000 so that a UI running in a host browser can connect to the /feed endpoint.

docker run --rm -it --network=telemetry \
    --name backend-core \
    -p 8000:8000 \
    --read-only \
    **substrate-telemetry-backend** \
    telemetry_core -l 0.0.0.0:8000
In another terminal, start up the backend shard process. We tell it where it can reach the core to send messages (possible because it has been started on the same network), and we listen on and expose port 8001 so that nodes running in the host can connect and send telemetry to it.

docker run --rm -it --network=telemetry \
    --name backend-shard \
    -p 8001:8001 \
    --read-only \
    **substrate-telemetry-backend** \
    telemetry_shard -l 0.0.0.0:8001 -c http://backend-core:8000/shard_submit

**Comment by dvdplm** [comment]
Thank you so much for the report, do you mind opening a PR with these fixes or do you prefer for us to take care of it?

/cc @chevdor

**Comment by decentration** [comment]
it seems that `name` in `default` in the `docker-compose.yaml` file is possibly in the incorrect place. If i just remove networks, default and name then it runs. Looking at older branches it was like this before.

**Comment by decentration** [comment]
Made a PR to correct this
https://github.com/paritytech/substrate-telemetry/pull/444

**Comment by jsdw** [comment]
@yayoi-k  the image names can be whatever we want; they are not the names of images searched for on docker, but are just the locally chosen names to present in the docker interfaces. 

@decentration having a gander at the docs (https://docs.docker.com/compose/networking/), it looks to me like the current YAML (below) is correct re network settings.

```
networks:
  default:
    name: substrate-telemetry
```

under the `networks` section you can configure a network for each of your named images, or `default` to configure the default. Under `default` we can then configure various things including the name, which is what this has done.

I don't think there would be any issue with just removing this `networks` section entirely and letting docker pick an arbitrary name, if it's causing some sort of issue.

**Comment by decentration** [comment]
I see what you’re saying, for some reason though it wasn’t working for me, I was getting an error that the string should be a mapping. Default network makes sense. Though something needs fixing, perhaps just indentation.

**Comment by jsdw** [comment]
Thanks for the feedback guys!

#447 hopefully addresses these comments. I've tested the docker-compose and the README steps and both seem OK now (I had to remove a `--read-only` which was causing an issue too in one case)
