### ISSUE TITLE
Can we get the telemetry data for Crust Network

### ISSUE THREAD

**Issue by mmyyrroonn** [paritytech/substrate-telemetry#438]
Hi. The crust network had some issues last week and finality got stuck at 2080276. Is there any data stored on the telemetry website https://telemetry.polkadot.io/#/0x8b404e7ed8789d813982b9cb4c8b664c05b3fbf433309f603af014ec9ce56a8c we can check for 2080250 - 2082000 to analyze the root cause?

**Comment by dvdplm** [comment]
Afraid not, telemetry does not store any data, it's all ephemeral. You'd need a proper block explorer for that, something like `substrate-archive` or subscan.

**Comment by mmyyrroonn** [comment]
> Afraid not, telemetry does not store any data, it's all ephemeral. You'd need a proper block explorer for that, something like `substrate-archive` or subscan.

All right. Thanks for the information.
