### ISSUE TITLE
Share k8s config for telemetry setup

### ISSUE THREAD

**Issue by Nexus2k** [paritytech/substrate-telemetry#442]
@lovelaced @arshamteymouri mind to share the k8s config for the telemetry setup or how are you hosting this? Our deployment helm chart is here: https://github.com/w3f/substrate-telemetry-chart but we're not sure if we could do better by scaling the backend shards etc.

**Comment by ArshamTeymouri** [comment]
The helm chart we use lives here: https://github.com/paritytech/helm-charts/tree/main/charts/substrate-telemetry
It supports HPA (horizontal pod autoscaling) for the `shard` service to dynamically scale up/down the replicas.
Please let me know if any information/help is needed.

**Comment by jsdw** [comment]
I'll close this for now, but pelase reopen if necessary :)
