### ISSUE TITLE
Add Individual Hardware Information to Telemetry Feed 

### ISSUE THREAD

**Issue by wpank** [paritytech/substrate-telemetry#479]
Right now all the new hardware information gets aggregated and sent in the `ChainStatsUpdate` feed message.

For things like the thousand validators programme, having this hardware data on a per node basis will help a lot with nominations, monitoring network health, and debugging.

For now I think it would be good to add this to the `AddedNode` Message, as this is what will get sent upon subscribing to the feed.

It would help to include three new messages:
- [NodeSysInfo](https://github.com/paritytech/substrate-telemetry/blob/master/backend/common/src/node_types.rs#L49)
- [NodeHwBench](https://github.com/paritytech/substrate-telemetry/blob/master/backend/common/src/node_types.rs#L66)
- IP Address

The IP Address part is also useful for determining infrastructure providers via various different apis.

**Comment by jsdw** [comment]
This issue prompted me to add #480.

I'd love to know precisely what information you currently want to obtain from telemetry over in that issue, so that we can see how easy/difficult it might be to expose a properly supported API that is separate from the frontend feed.

**Comment by wpank** [comment]
closed via #519
