### ISSUE TITLE
The Aleph Zero telemetry page is swarmed with shadows.

### ISSUE THREAD

**Issue by DamianStraszak** [paritytech/substrate-telemetry#508]
When you open https://telemetry.polkadot.io/#list/0x05d5279c52c484cc80396535a316add7d47b1c5b9e0398dd1f584149341460c5 you will see lots of nodes (which are duplicates of existing ones) which are at block `0` (see the attached screenshot)
![Screenshot from 2022-11-04 12-40-12](https://user-images.githubusercontent.com/23038619/199964299-55b91405-6f95-4cb0-901d-044ed3c928a3.png)

The reason why these entries showed up in the first place seems to be caused by a mistake on our side -- our node runner mistakenly attached the CLI argument `"--telemetry-url \'wss://telemetry.polkadot.io/submit/ 1\'"` twice. This is now fixed on our side, but the shadow entries don't want to disappear. This must be some backend issue, because we also run our own frontend and it looks the same as the polkadot one.

**Comment by jsdw** [comment]
Interesting, yes, sorting by names there are a bunch of "duplicate" nodes.

Telemetry should disconnect any entries which are not updated (see https://github.com/paritytech/substrate-telemetry/blob/4ae06f48bf223f2fcd634ba58e1dbd0cfc31b15c/backend/telemetry_shard/src/main.rs#L288). So, my guess is that either those nodes are still connected and sending some sort of message to keep the entries  alive, or the code to tidy up individual nodes from some connection isn't doing its job properly.

**Comment by DamianStraszak** [comment]
Hi! 

I have just now created a new entry `damian-krk` using the following method
1. Run the node, but repeat the parameter `--telemetry-url='wss://telemetry.polkadot.io/submit/ 1'` twice in our (quite standard) substrate node.
2. Kill it after 2 mins.
3. There are now 2 new shadows `damian-krk` with `0` blocks. And they are not going away, even though might node is off for some time (and this is exactly the same for other shadow entries, they were off for >2 days).

So I think there must indeed be an issue with cleaning up bad entries.

**Comment by DamianStraszak** [comment]
Hi!
Did you manage to take a look at this?

**Comment by jsdw** [comment]
Hey! Ah I'm afraid not; I've been very busy this last month, and I'm afraid I won't be around much next month either! @paritytech/tools-team if any of you guys have time to dig into this it could be a good chance to dig into the telemetry code a bit more :)

**Comment by jsdw** [comment]
@Xanewok has opened a PR which we'll aim to deploy fairly soon!

In looking into this, it seems that passing the telemetry URl twice basically causes two of every message to be sent to the telemetry server, so I'd strongly recommend _not_ doing that as you might spot other glitches with the way your nodes are updating due to that (and it's generally a waste of effort on the telemetry side to handle the duplicates) :)

**Comment by DamianStraszak** [comment]
Thanks for the fix -- looks great!

Did you manage to deploy the new version already? As it seems that the old shadows are still there on the official polkadot telemetry.

**Comment by Xanewok** [comment]
It's deployed just now. Could you take a look and verify that everything looks okay?

**Comment by DamianStraszak** [comment]
Absolutely brilliant! Thank you :heart:
