### ISSUE TITLE
server location

### ISSUE THREAD

**Issue by SixoneKui** [paritytech/substrate-telemetry#566]
I am running a node with could server Hetzner.

The server should be in  West US, but https://telemetry.polkadot.io/#/0xfc41b9bd8ef8fe53d58c7ea67c794c7ec9a73daf05e6d54b14ff6342c99ba64c shows the location as somewhere in the middle east？

Many thanks.

**Comment by jsdw** [comment]
We just merged an external PR to update the DB so hopefully this will be resolved now!
