### ISSUE TITLE
Unable to horizontal scroll to view all Substrate and Polkadot testnet chain tabs

### ISSUE THREAD

**Issue by ltfschoen** [paritytech/substrate-telemetry#92]
Screenshot showing Github logo overlapping the testnet chain tabs <img width="219" alt="screen shot 2019-02-01 at 8 18 36 am" src="https://user-images.githubusercontent.com/6226175/52086046-0d7f2980-25fa-11e9-8e9e-f7b976e4852d.png">

**Comment by maciejhirsz** [comment]
This has been fixed in #157.
