### ISSUE TITLE
A punished validator node still shows as a validator node in telemetry

### ISSUE THREAD

**Issue by Kalanamith** [paritytech/substrate-telemetry#96]
**Scenario**

- Create a full node using docker.
- Create an account.
- Restart the full node as a validator node with the key.
- Stake the account.
- Wait till it becomes a validator.

**Observation**
- After sometimes check the `validators` section on staking overview.  
- You may find the newly added validator is no longer presents.
- Telemetry will still shows the node as a validator node.

**Note**

Newly added validator node kicked out from the network after 15 or 30 minutes.
This happens most of the time

**Comment by Kalanamith** [comment]
@gavofyork Thanks!

**Comment by chevdor** [comment]
Telemetry listing all the node advertising themselves as validator, if you want to prune the list, telemetry will have to decide on what is a bad node and what is a good one.

A validator that has been kicked is not always a bad validator. It may be a legit one, that has been kicked simply! It may be back and be good forever.

What could be done however assuming validator nodes don´t lie (hmm, hmm...) would be to keep track of the number of times a validator was slashes and show/sort based on that value.

That also means that telemetry would have to persist its data, which is nothing something done today.
